library(dplyr)
library(here)
df <- readRDS(here("R", "pcs_processed.rds"))
cat("childre3 summary:\n")
print(table(df$childre3, useNA="always"))
cat("chngchildre4 summary:\n")
print(table(df$chngchildre4, useNA="always"))
cat("income3 summary:\n")
print(table(df$income3, useNA="always"))
