library(dplyr)
library(here)
df <- readRDS(here("R", "pcs_processed.rds"))

cat("movie3:\n")
print(table(df$movie3, useNA="always"))
cat("movie4:\n")
print(table(df$movie4, useNA="always"))
cat("movie5:\n")
print(table(df$movie5, useNA="always"))

cat("\nSummary of video usage:\n")
print(table(df$videos3, useNA="always"))
print(table(df$videos4, useNA="always"))
print(table(df$videos5, useNA="always"))
