library(dplyr)
library(here)
df <- readRDS(here("R", "pcs_processed.rds"))
cat("movie3:\n")
print(table(df$movie3, useNA="always"))
cat("play3:\n")
print(table(df$play3, useNA="always"))
cat("spevent3:\n")
print(table(df$spevent3, useNA="always"))
